/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCoursePage: typeof import('./src/components/AddCoursePage.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
